# Numpy的介绍

In [2]:
# 导包
import numpy as np

# 创建一个二维数组对象
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# print(type(arr))
# print(arr)
# arr

print(arr.ndim)  # 维度
print(arr.shape)  # 形状
print(arr.size)  # 元素个数
print(arr.dtype)  # 数据类型
print(arr.itemsize)  # 每个元素字节数大小

2
(3, 3)
9
int64
8


## adarray对象的创建

In [3]:
# array(): 将输入数据转换为ndarray,会进行copy
# asarray(): 将输入数据转换为ndarray,如果输入本身是ndarray则不会copy

list1 =[1,2,3]
print(list1,id(list1),type(list1))

arr1 = np.array(list1)
print(arr1,id(arr1),type(arr1))

arr2 = np.asarray(list1)
print(arr2,id(arr2),type(arr2))

arr3 = np.array(arr1)
print(arr3,id(arr3),type(arr3))

arr4 = np.asarray(arr1)
print(arr4,id(arr4),type(arr4))

[1, 2, 3] 1596696803520 <class 'list'>
[1 2 3] 1596675503760 <class 'numpy.ndarray'>
[1 2 3] 1596675159024 <class 'numpy.ndarray'>
[1 2 3] 1596675159120 <class 'numpy.ndarray'>
[1 2 3] 1596675503760 <class 'numpy.ndarray'>


In [4]:
# zeros()、ones()、empty()与zeros_like()、ones_like()、empty_like()

# zeros()：返回给定形状和类型的新数组，用0填充。
arr = np.zeros((2,3),dtype='int64')
# arr.dtype

# ones()：返回给定形状和类型的新数组，用1填充。
np.ones((3,4))

# empty()：返回给定形状和类型的未初始化的新数组。
np.empty((4,5))

arr1 = np.zeros((2,3),dtype='int64')
np.zeros_like(arr1)
np.ones_like(arr1)
np.empty_like(arr1)     # 内存复用导致的跟前面一样

array([[1, 1, 1],
       [1, 1, 1]])

In [5]:
# full()：返回给定形状和类型的新数组，用指定的值填充。
# full_like()：返回与给定数组具有相同形状和类型的用指定值填充的新数组。
arr = np.full((2, 3), 66)
np.full_like(arr, 77)



array([[77, 77, 77],
       [77, 77, 77]])

In [6]:
# arange()：返回在给定范围内用均匀间隔的值填充的一维数组。不包括结尾
np.arange(0,20,4)

array([ 0,  4,  8, 12, 16])

In [7]:
# linspace()：返回指定范围和元素个数的等差数列。数组元素类型为浮点型。
# logspace()：返回指定指数范围、元素个数、底数的等比数列。

np.linspace(start=0,stop=20,num=5,endpoint=False)       #
np.logspace(start=2,stop=8,num=3,endpoint=False,base=3)     # 指数取2,4,6

array([ 0.,  4.,  8., 12., 16.])

In [8]:
# random.rand()：返回给定形状的数组，用 [0, 1) 上均匀分布的随机样本填充。
np.random.rand(3,4)
# random.randint()：返回给定形状的数组，用从低位(包含)到高位(不包含)上均匀分布的随机整数填充。
np.random.randint(low=3,high=10,size=(2,3))
# random.uniform()：返回给定形状的数组，用从低位(包含)到高位(不包含)上均匀分布的随机浮点数填充。
np.random.uniform(low=3,high=10,size=(2,3))
# random.randn()：返回给定形状的数组，用标准正态分布(均值为0，标准差为1)的随机样本填充。
np.random.randn(3,4)


array([[ 1.39142773, -2.42103211, -1.78882831,  1.7415657 ],
       [ 0.01788143,  0.41113894,  0.26301669, -1.34845628],
       [ 0.5224907 , -0.41151822,  0.10883056,  1.49264912]])

In [9]:
# matrix为ndarray的子类，只能生成二维的矩阵
arr = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
type(arr)
np.matrix("1 2; 3 4; 5 6")

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [10]:
# 在创建数组对象的时候    指定数组中元素的类型  具体种类和内存量看文档
arr = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype='int64')
arr = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype='f8')

arr.astype('i8')
arr.astype(np.float64)


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [21]:
# ndarray的切片和索引
arr = np.arange(11)
arr
# 获取索引为2的数据
arr[2]
# 从索引2开始到索引9(不包含)停止,间隔为2
arr[2:9:2]
arr[slice(2,9,2)]
# 从索引2开始到最后,默认间隔为1
arr[2:]

# 从索引2开始到索引9(不包含)结束,默认间隔为1
arr[2:9]

# 取前2行前2列
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr
arr[0:2,0:2]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# 基本函数

In [22]:
arr = np.array([[1.3,-2.5,3.3],[-4.1,np.nan,6],[7,8.2,-9]])

# np.abs()	元素的绝对值，参数是 number 或 array
np.abs(arr)

# np.ceil()	向上取整，参数是 number 或 array
np.ceil(arr)

# np.floor()	向下取整，参数是 number 或 array
np.floor(arr)

# np.rint()	四舍五入，参数是 number 或 array
# 四舍六入：当需要舍入的数字小于 5 时，直接舍去；当需要舍入的数字大于 5 时，进位。
# 五成双：当需要舍入的数字恰好是 5 时，会看 5 前面的数字，如果是偶数则直接舍去 5，如果是奇数则进位。
np.rint(4.5)

# np.isnan()	判断元素是否为NaN(Not a Number) ，参数是 number 或 array
np.isnan(arr)       # nan是float类型

# np.multiply()	元素相乘，参数是 number 或 array。如果第二个参数传递的是number，原数组中所有元素乘以这个数字，返回新的数组；如果第二个参数也是一个数组，是将两个数组中对应位置的元素相乘，返回一个新的数组，其形状与输入数组相同。
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1 = np.array([[10,20,30],[40,50,60],[70,80,90]])
np.multiply(arr,2)
np.multiply(arr,arr1)   # 对应元素相乘

# np.divide()	元素相除，参数是 number 或 array
np.divide(arr,2)
np.divide(arr,arr1)

# np.where(condition, x, y)	三元运算符，满足条件返回x,不满足返回y
np.where(arr > 3,66,77)


array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

# 统计函数

In [26]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# np.mean()	所有元素的平均值    axis=0 沿着行的方向(垂直) 对列数据进行统计      axis=1 沿着列的方向(水平) 对行数据进行统计
np.mean(arr,axis=0)

# np.sum()	所有元素的和
np.sum(arr,axis=1)

# np.max()	所有元素的最大值
np.max(arr,axis=0)
# np.min()	所有元素的最小值

# np.std()	所有元素的标准差
# np.var()	所有元素的方差
np.std(arr)
np.var(arr)

# np.argmax()	最大值的下标索引值
# np.argmin()	最小值的下标索引值
np.argmax(arr,axis=0)

# np.cumsum()	返回一个一维数组，每个元素都是之前所有元素的累加和
np.cumsum(arr,axis=1)

# np.cumprod()	返回一个一维数组，每个元素都是之前所有元素的累乘积
np.cumprod(arr,axis=0)


array([2, 2, 2])

# Any和All

In [14]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
# np.any()	至少有一个元素满足指定条件，就返回一个True
np.any(arr > 3)
# np.all()	所有的元素都满足指定条件，才返回一个True
np.all(arr > 3)


np.False_

#  排序函数

In [15]:
arr = np.array([[9,3,2],[6,7,4],[1,5,8]])
arr
# 注意: 如果没有指定axis参数,不是对整个数组进行排序,默认值是-1,表示沿着最后一个轴进行排序
# 在二维数组中,最后一轴是列,和axis=1效果一样
# ndarray.sort()：就地排序（直接修改原数组）。
arr.sort(axis=1)
arr

# np.sort()：返回排序后的副本（创建新的数组）。
arr = np.array([[9,3,2],[6,7,4],[1,5,8]])
np.sort(arr,axis=0)

array([[1, 3, 2],
       [6, 5, 4],
       [9, 7, 8]])

# 去重函数

In [16]:
# np.unique()：计算唯一值并返回有序结果。
arr1 = np.random.randint(0, 5, (3, 3))
print(arr1)
np.unique(arr1)

[[1 2 3]
 [0 2 2]
 [0 4 2]]


array([0, 1, 2, 3, 4], dtype=int32)

# 基本运算

In [17]:
# 数组和数组之间进行运算-----对位运算
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [18]:
# 数组和标量(常数值)进行运算       将标量值传播到各个元素
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1 + 100)
print(arr1 - 100)
print(arr1 * 100)
print(arr1 / 100)


[[101 102 103]
 [104 105 106]]
[[-99 -98 -97]
 [-96 -95 -94]]
[[100 200 300]
 [400 500 600]]
[[0.01 0.02 0.03]
 [0.04 0.05 0.06]]


# 不同大小的数组之间的运算的广播机制

In [19]:
# 广播机制是 NumPy 中一个强大的特性，它允许在不同形状的数组之间进行元素级运算。广播机制的规则如下：
# 	规则1：如果俩个数组的维度数不相同，那么小维度数组的形状将会在最左边补1。
# 	规则2：如果俩个数组的形状在任何一个维度上都不匹配，那么数组的形状会沿着维度大小（元素个数）为1的维度开始扩展 ，（维度必须是1开始）直到所有维度都一样， 以匹配另一个数组的形状。
arr1 = np.array([1,2,3])    # (3,)
arr2 = np.array([[1],[2],[3]])  # (3,1)
# arr1: (3,)->(1,3)->(3,3)
# arr2: (3,1)->(3,3)
print(arr1 + arr2)
#	规则3：如果俩个数组的形状在任何一个维度上都不匹配，并且没有任何一个维度大小等于1，那么会引发异常。
# 一维数组
arr3 = np.array([1, 2, 3])  # 形状为 (3,)
# 一维数组
arr4 = np.array([4, 5])  # 形状为 (2,)
#     result = arr3 + arr4   # 只满足规则1
arr5 = np.array([6, 7, 8])  # (3,)
arr6 = np.array([3])    #(1,)->(3,)
print(arr5 + arr6)      # arr6: (1,)满足规则2可以加


[[2 3 4]
 [3 4 5]
 [4 5 6]]
[ 9 10 11]


# 矩阵乘法

In [20]:
# 运算符 np.dot()、ndarray.dot()、@
# 前提: 第一个矩阵的列数等于第二个矩阵的行数
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[6, 5], [4, 3], [2, 1]])

arr1 @ arr2
np.dot(arr1,arr2)
arr1.dot(arr2)

array([[20, 14],
       [56, 41]])

# 习题

In [39]:
# 重塑 np.reshape()
# 把一维数组变为2行5列
arr = np.arange(1,11)
np.reshape(arr,(2,5))

# 创建一个3*4的二维数组,并用[1,5]的随机整数进行填充
arr1 = np.random.randint(1,6,size=(3,4))

# 取出上述数组的前两行和后三列
arr1[:2]
arr1[1:]

array([[1, 5, 4, 3],
       [2, 1, 2, 3]], dtype=int32)