# Numpy的介绍

In [12]:
# 导包
import numpy as np

# 创建一个二维数组对象
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# print(type(arr))
# print(arr)
# arr

print(arr.ndim)  # 维度
print(arr.shape)  # 形状
print(arr.size)  # 元素个数
print(arr.dtype)  # 数据类型
print(arr.itemsize)  # 每个元素字节数大小

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9
int64
8


## adarray对象的创建

In [17]:
# array(): 将输入数据转换为ndarray,会进行copy
# asarray(): 将输入数据转换为ndarray,如果输入本身是ndarray则不会copy

list1 =[1,2,3]
print(list1,id(list1),type(list1))

arr1 = np.array(list1)
print(arr1,id(arr1),type(arr1))

arr2 = np.asarray(list1)
print(arr2,id(arr2),type(arr2))

arr3 = np.array(arr1)
print(arr3,id(arr3),type(arr3))

arr4 = np.asarray(arr1)
print(arr4,id(arr4),type(arr4))

[1, 2, 3] 2977223122624 <class 'list'>
[1 2 3] 2977200818192 <class 'numpy.ndarray'>
[1 2 3] 2977201082448 <class 'numpy.ndarray'>
[1 2 3] 2977200818096 <class 'numpy.ndarray'>
[1 2 3] 2977200818192 <class 'numpy.ndarray'>
